language: r
dist: bionic
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/nLTT
  - ropensci/spelling
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt install -qq libmpfr-dev
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # proselint
  - sudo pip install proselint

script:
  - echo "Caching packages"
  #- travis_wait 60 R CMD build .
  #- travis_wait 60 R CMD check *tar.gz

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links

after_failure:
  - cat /home/travis/build/richelbilderbeek/peregrine/peregrine.Rcheck/00check.log
