language: r
dist: bionic
cache: packages

r_github_packages:
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - richelbilderbeek/babette
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling
  - richelbilderbeek/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette

before_install:
  - sudo apt-get update
  # ImageMagick
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt install -qq libmpfr-dev
  # proselint
  - sudo pip install proselint

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  - cd scripts && ./install_mhcnuggetsr.sh

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links

after_failure:
  - cat /home/travis/build/richelbilderbeek/peregrine/peregrine.Rcheck/00check.log
  - cat /home/travis/build/richelbilderbeek/peregrine/peregrine.Rcheck/00install.out

